# Generated by Django 3.2.4 on 2021-06-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hcollections', '0001_initial'),
        ('carts', '0002_auto_20210626_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='hcollection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hcollections.hcollection'),
        ),
    ]
