# Generated by Django 3.2.4 on 2021-06-27 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hcollections', '0001_initial'),
        ('carts', '0004_remove_cart_hcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hcollection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hcollections.hcollection'),
            preserve_default=False,
        ),
    ]
