# Generated by Django 3.2.4 on 2021-06-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_hcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='hcollection',
        ),
    ]
