# Generated by Django 3.2.4 on 2021-06-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='images/category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Mealcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hcollections.category')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('meal_image', models.ImageField(null=True, upload_to='images/meal_images')),
                ('is_active', models.BooleanField(default=True)),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hcollections.mealcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Hcollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('available_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hcollection_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/hcollection_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hcollections.category')),
            ],
        ),
    ]
