# Generated by Django 3.2.4 on 2021-06-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_buyer_seller'),
        ('Hcollections', '0003_alter_usermembership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.buyer'),
            preserve_default=False,
        ),
    ]
